### ISSUE TITLE
Test "correctly redirects for a file whose filename contains something looking like a hash" does not validate assumption

### ISSUE THREAD

**Issue by bcullman** [mediocre/electricity#37]
The test "correctly redirects for a file whose filename contains something looking like a hash" never verifies that the bool "redirected" bool was set to true.

I created a pull request (https://github.com/mediocre/electricity/pull/36) that adds the missing assert, but it causes a new problem - the test does not pass.

The path provided in the test "/robots-3e.txt" is dehashified to "/robots.txt", which is then hashified to "/robots-ca121b5d03245bf82db00d14cee04e22.txt". This is not match for the expected url. The added assert now shows a failure.

Either we should change the expected value in the test to "/robots-ca121b5d03245bf82db00d14cee04e22.txt"
OR
We should ONLY dehashify urls that contain actual 32 character hashes

I am not certain why we would want to redirect for filenames that have something that looks like a hash, rather than actually having a hash.

**Comment by Harrison-M** [comment]
Got the test to pass and merged. Just needed a check to make sure a match exists. Thanks for the PR!
