### ISSUE TITLE
Have uglify-js minification support ES6 JavaScript

### ISSUE THREAD

**Issue by cvan** [mediocre/electricity#56]
[`uglify-js`](https://www.npmjs.com/package/uglify-js) supports only ES5 code.

I started a new branch using [`babel-minify`](https://www.npmjs.com/package/babel-minify), but I decided that **[`uglify-es`](https://www.npmjs.com/package/uglify-es)** is likely the more appropriate library to use, since electricity is designed today for only minifying JS (not transpiling and minifying, which is slower and not always what developers would want). (If folks want Babel transpiling and minifying, I suppose a follow-up issue could be filed for that.)

Here are some examples of the JS that `uglify-js` was choking on:

```js
(() => {
```

fails with

```shell
UglifyJS skipping /opt/project/static/js/index.js:
    {"message":"Unexpected token: punc ())","filename":"0","line":2,"col":2,"pos":76}
```

and

```js
class Store {
```

fails with

```shell
UglifyJS skipping /opt/project/static/js/vendor/idb-keyval/3.1.0/dist/idb-keyval-iife.js:
    {"message":"Unexpected token: name (Store)","filename":"0","line":4,"col":6,"pos":59}
```

**Comment by talentlessguy** [comment]
Another option is to switch to [Terser](https://github.com/terser/terser)

it's faster and supports modern syntax better

**Comment by freshlogic** [comment]
uglify-es has been deprecated. switched back to uglify-js
